language: python
sudo: false
cache:
    apt: true
    directories:
    - "$TRAVIS_BUILD_DIR/build/GSL/src"
    - "$TRAVIS_BUILD_DIR/build/FFTW/src"
    - "$TRAVIS_BUILD_DIR/build/SWIG/src"
    - "$HOME/libsharp"
    - "$HOME/miniconda"
    pip: true

addons:
    apt:
        packages:
            - libfftw3-3
            - autotools-dev
            - autoconf
            - libcfitsio-bin
            - libcfitsio-dev

matrix:
  include:
  - os: linux
    python: 2.7
    sudo: required
    env: TOXENV=py27
  - os: linux
    sudo: required
    python: 3.6
    env: TOXENV=py36
  #- os: osx
  #  osx_image: xcode9.4
  #  language: generic
  #  env: TOXENV=py27
  #- os: osx
  #  osx_image: xcode9.4
  #  language: generic
  #  env: TOXENV=py36

before_install:
- "chmod 777 ./.travis/install.sh"

install:
- "./.travis/install.sh"

script:
- python setup.py install
