language: python
sudo: false
cache:
    apt: true
    directories:
    - "$TRAVIS_BUILD_DIR/build/GSL/src"
    - "$TRAVIS_BUILD_DIR/build/FFTW/src"
    - "$TRAVIS_BUILD_DIR/build/SWIG/src"
    - "$HOME/libsharp"
    - "$HOME/miniconda"
addons:
    apt:
        packages:
            - gsl-bin
            - libgsl0-dev
            - libgsl0ldbl
            - libfftw3-3
            - autotools-dev
            - autoconf
matrix:
  include:
  - os: linux
    python: 2.7
    sudo: required
    env: TOXENV=py27
  - os: linux
    sudo: required
    python: 3.6
    env: TOXENV=py36
  #- os: osx
  #  osx_image: xcode9.4
  #  language: generic
  #  env: TOXENV=py27
  #- os: osx
  #  osx_image: xcode9.4
  #  language: generic
  #  env: TOXENV=py36
install:
- "./.travis/install.sh"
- if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then source $HOME/miniconda/bin/activate;
  fi
- if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then hash -r ; fi
- if ! [[ $TRAVIS_OS_NAME == "linux" ]]; then source activate test-environment ; fi
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
- python --version
script:
- python setup.py install
